-- Read-only: run after deployment. All retired/policy/definition arrays must be empty.
with retired_tables(name) as (values ('birthday_benefit_grants'),
('birthday_benefit_settings')),
retired_columns(table_name,column_name) as (values ('event_tickets','required_service_types'),
('event_tickets','redemption_latitude'),
('event_tickets','redemption_longitude'),
('event_tickets','redemption_radius_meters'),
('point_card_rewards','required_service_types'),
('event_ticket_settings','max_tickets_per_redemption'),
('test_mode_settings','enabled'),
('test_mode_settings','allow_admin_user_login'),
('booking_services','work_start_time'),
('booking_services','work_end_time'),
('booking_services','slot_minutes'),
('booking_services','min_advance_days'),
('booking_services','available_weekdays')),
retired_functions(name,identity) as (values ('admin_save_test_mode','p_enabled boolean, p_allow_admin_user_login boolean, p_maintenance_message text, p_updated_by text, p_add_account_count integer'),
('admin_save_test_mode_v2','p_test_mode_enabled boolean, p_maintenance_enabled boolean, p_maintenance_message text, p_updated_by text, p_add_account_count integer'),
('admin_save_test_mode_v3','p_test_mode_enabled boolean, p_maintenance_enabled boolean, p_allow_pc_test_login boolean, p_allow_mobile_test_login boolean, p_maintenance_message text, p_updated_by text, p_add_account_count integer'),
('booking_has_required_service_id','p_booking_id uuid, p_required_service_ids uuid[]'),
('booking_has_required_service_type','p_booking_id uuid, p_required_service_types text[]'),
('complete_booking_with_receipt_request','p_receipt_id text, p_member_id uuid, p_actor_line_user_id text, p_expected_booking_updated_at timestamp with time zone, p_actual_mime_type text, p_actual_size_bytes integer, p_sha256_hex text'),
('create_booking_request','p_request_id text, p_service_id uuid, p_member_id uuid, p_booking_date date, p_start_time time without time zone, p_member_note text'),
('issue_birthday_benefits','p_business_date date'),
('prevent_delete_ticket_required_service_type',''),
('register_accessible_receipt_request','p_receipt_id text, p_expected_receipt_updated_at timestamp with time zone, p_actor text, p_booking_id uuid, p_booking_date date, p_start_time time without time zone, p_items jsonb, p_admin_note text'),
('rename_booking_service_type','p_type_id uuid, p_name text, p_actor text'),
('save_booking_settings_with_service_types','p_work_start_time time without time zone, p_work_end_time time without time zone, p_min_advance_days integer, p_service_types text[], p_expected_updated_at timestamp with time zone, p_actor text'),
('save_booking_shared_settings','p_work_start_time time without time zone, p_work_end_time time without time zone, p_min_advance_days integer, p_booking_notice text, p_expected_updated_at timestamp with time zone, p_actor text'),
('save_booking_shared_settings','p_work_start_time time without time zone, p_work_end_time time without time zone, p_min_advance_days integer, p_max_advance_days integer, p_booking_notice text, p_expected_updated_at timestamp with time zone, p_actor text'),
('save_booking_shared_settings_v2','p_work_start_time time without time zone, p_work_end_time time without time zone, p_min_advance_days integer, p_max_advance_days integer, p_booking_notice text, p_store_service_minutes integer, p_expected_updated_at timestamp with time zone, p_actor text'),
('sync_legacy_ticket_redemption_location',''),
('sync_legacy_ticket_required_service_types_to_ids',''),
('sync_ticket_required_service_type_name',''))
select jsonb_build_object(
 'public_table_count',(select count(*) from pg_tables where schemaname='public'),
 'public_function_count',(select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prokind in ('f','p') and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
 'retired_tables_present',(select coalesce(jsonb_agg(name),'[]') from retired_tables where to_regclass('public.'||name) is not null),
 'retired_columns_present',(select coalesce(jsonb_agg(r.table_name||'.'||r.column_name),'[]') from retired_columns r join information_schema.columns a on a.table_schema='public' and a.table_name=r.table_name and a.column_name=r.column_name),
 'retired_functions_present',(select coalesce(jsonb_agg(p.proname||'('||pg_get_function_identity_arguments(p.oid)||')'),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace join retired_functions r on r.name=p.proname and r.identity=pg_get_function_identity_arguments(p.oid) where n.nspname='public'),
 'obsolete_definition_references',(select coalesce(jsonb_agg(n.nspname||'.'||p.proname),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','maintenance','booking_notifications','private','line_config') and p.prokind in ('f','p') and pg_get_functiondef(p.oid) ~ '(birthday_benefit_settings|birthday_benefit_grants|required_service_types|redemption_latitude|redemption_longitude|redemption_radius_meters|allow_admin_user_login|slot_minutes|available_weekdays)'),
 'rls_disabled_public_tables',(select coalesce(jsonb_agg(c.relname),'[]') from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity),
 'updated_rpc_public_execution',(select coalesce(jsonb_agg(p.proname),'[]') from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prorettype <> 'trigger'::regtype and p.proname in ('save_point_card','bind_member_referral','apply_fixed_ticket_location_rule','admin_delete_test_accounts','admin_purge_test_data','admin_save_maintenance_test_access','admin_prepare_complex_e2e_fixtures','count_today_usable_event_tickets','redeem_event_ticket','redeem_event_tickets_with_location') and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE'))),
 'active_cron_job_count',(select count(*) from cron.job where active)
) as verification;
