const fs = require('node:fs');
const assert = require('node:assert/strict');

const read = (path) => fs.readFileSync(path, 'utf8');

const adminPanel = read('MemberWebsocket-dev/admin/booking-panel-core.js');
const bookingIndex = read('MemberWebsocket-dev/booking/index.html');
const calendarFlow = read('MemberWebsocket-dev/booking/calendar-flow.js');
const holidayTheme = read('MemberWebsocket-dev/booking/calendar-holiday-theme.css');
const adminApi = read('MemberWebsocket-dev/supabase/functions/booking-admin-api/index.ts');
const calendarApi = read('MemberWebsocket-dev/supabase/functions/booking-calendar-api/index.ts');
const migration = read('MemberWebsocket-dev/supabase/migrations/20260910235500_booking_notice_holiday_block.sql');

assert.match(adminPanel, /bookingAdminNotice/);
assert.match(adminPanel, /bookingNotice/);
assert.match(adminPanel, /admin\.booking\.settings\.save/);
assert.match(adminApi, /save_booking_shared_settings/);
assert.match(adminApi, /bookingNotice/);
assert.match(calendarApi, /calendar_items/);
assert.match(calendarApi, /item_type", "holiday/);
assert.match(calendarApi, /calendar_item_id,title,description,starts_on,ends_on,accent/);
assert.match(calendarApi, /accent: String\(row\.accent/);
assert.match(calendarApi, /bookingNotice/);
assert.match(calendarApi, /async function requireJoinedMember\([\s\S]*Promise<\{ id: string; membership_status: string; status: string \}>/);
assert.match(calendarApi, /\.eq\("member_id", memberId\)/);
assert.match(calendarApi, /const member = await requireJoinedMember\(supabase, identity\)/);
assert.match(calendarApi, /loadCalendar\(supabase, month, member\.id\)/);
assert.match(calendarFlow, /holidaysByDate/);
assert.match(calendarFlow, /休假日，無法預約/);
assert.match(calendarFlow, /showHolidayNotice/);
assert.match(calendarFlow, /textContent = description/);
assert.match(calendarFlow, /accent: safeHolidayAccent\(raw\?\.accent\)/);
assert.match(calendarFlow, /applyHolidayAccent\(button, holidays\[0\]\?\.accent\)/);
assert.match(calendarFlow, /applyHolidayAccent\(item, holiday\.accent\)/);
assert.match(calendarFlow, /\$\{interval\.startTime\}–\$\{interval\.endTime\} 我的預約/);
assert.match(calendarFlow, /有 \$\{intervals\.length\} 個我的預約時段/);
assert.match(bookingIndex, /我的預約時段/);
assert.match(calendarFlow, /if \(date === today\) button\.classList\.add\('today'\)/);
assert.doesNotMatch(bookingIndex, /appointment-date-bar/);
assert.doesNotMatch(bookingIndex, /changeDateButton/);
assert.doesNotMatch(bookingIndex, /選其他日期/);
assert.doesNotMatch(calendarFlow, /changeDateButton/);
assert.match(bookingIndex, /calendar-flow\.css\?v=booking-remove-date-bar-20260919-1/);
assert.ok(bookingIndex.includes('calendar-flow.js?v=booking-single-render-20260919-1'));
assert.doesNotMatch(calendarFlow, /ackBookingHolidayButton/);
assert.doesNotMatch(calendarFlow, />知道了</);
assert.match(bookingIndex, /calendar-holiday-theme\.css\?v=booking-calendar-holiday-theme-20260916-2/);
assert.match(holidayTheme, /#calendarGrid \.calendar-day\.holiday-disabled\.today/);
assert.match(holidayTheme, /#calendarGrid \.calendar-day\.holiday-disabled\.today::after/);
assert.match(holidayTheme, /border: 2px solid rgba\(223, 107, 77, \.82\)/);
assert.match(holidayTheme, /pointer-events: none/);
assert.match(holidayTheme, /#calendarGrid \.calendar-holiday-label/);
assert.match(holidayTheme, /background: var\(--holiday-accent, #df6b4d\)/);
assert.match(holidayTheme, /color: var\(--holiday-foreground, #000000\)/);
assert.match(holidayTheme, /#calendarGrid \.calendar-holiday-label::before/);
assert.match(holidayTheme, /@media \(max-width: 430px\)/);
assert.match(holidayTheme, /height: 5px/);
assert.match(holidayTheme, /#bookingHolidayModal \.booking-holiday-detail/);
assert.match(migration, /booking_notice/);
assert.match(migration, /prevent_booking_on_active_holiday/);
assert.match(migration, /BOOKING_HOLIDAY/);
assert.match(migration, /status = 'active'/);

console.log('booking notice/holiday wiring OK');
